version: "3"

volumes: 
    shareddata:

### Join existing network "env_rede"
# networks:
  # default:
    # external:
      # name: env_rede
### Create a new network      
networks:
  mynetwork1:

services:

  alpine:
    image: "alpine:latest"    
    container_name: alpine
    command: tail -F anything
    #ports:
    #  - "135:135"    
    hostname: alpine    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
      
  busybox:
    image: "busybox"
    container_name: busybox    
    volumes:
      - /data
    command: tail -F anything
    #ports:
    #  - "135:135"    
    hostname: busybox    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
           
  # dotnetsdk:
    # image: "mcr.microsoft.com/dotnet/core/sdk:2.2"
    # container_name: dotnetsdk
    # #command: pwsh -Command Test-Connection -TargetName sambaalpine -IPv4 -Count 3 -Delay 3
    # stdin_open: true    
    # hostname: dotnetsdk    
    # environment:
      # - VAR1=var1
    # networks:
      # - mynetwork1
      
  sambaalpine:
    image: "stevepacker/samba-alpine"
    container_name: sambaalpine
    ports:
      - "8135:135"
      - "8137:137/udp"
      - "8138:138/udp"
      - "8139:139"
      - "8445:445"
    hostname: sambaalpine
    volumes:
      - shareddata:/shared
      - ~/:/public
    environment:
      - DIRECTORIES=shared,public
      - WORKGROUP=WORKGROUP
      - SAMBA_NAME=sambaalpine
      ###//only if Directories are not defined and only one volume shared  
      #- SHARE_NAME=shared   
    networks:
      - mynetwork1
   
      
  powershell:
    image: "mcr.microsoft.com/powershell:latest"
    container_name: powershell
    command: pwsh -Command Test-Connection -TargetName sambaalpine -IPv4 -Count 3 -Delay 3
    stdin_open: true    
    hostname: powershell    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
    depends_on:
      - sambaalpine
    
    