version: "3"

volumes: 
    shareddata:

networks:
    mynetwork1: 

services:

  alpine:
    image: "alpine:3.6"    
    container_name: alpine
    command: tail -F anything
    #ports:
    #  - "80:80"    
    hostname: alpine    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
      
  busybox:
    image: "busybox"
    container_name: busybox
    volumes:
      - /data
    command: tail -F anything
    #ports:
    #  - "80:80"    
    hostname: busybox    
    environment:
      - VAR1=var1
    networks:
      - mynetwork1
      
  sambaalpine:
    image: "stevepacker/samba-alpine"
    container_name: sambaalpine
    ports:
      - "8135:135"
      - "8137:137"
      - "8138:138"
      - "8139:139"
      - "8445:445"
    hostname: sambaalpine
    volumes:
      - shareddata:/shared
      - ~/:/public
    environment:
      - DIRECTORIES=shared,public
      - WORKGROUP=WORKGROUP
      - SAMBA_NAME=sambaalpine
      ###[SHARE_NAME]-> Define only if [DIRECTORIES] are not defined and only one volume shared
      #- SHARE_NAME=shared     
     networks:
       - mynetwork1
     depends_on:
       - alpine
    
    