name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
      
    - name: Test
      run: dotnet test dotnet build
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish NuGet
      uses: rohith/publish-nuget@v1.2.0
      with:
        # Project (csproj) directory path relative from the root of repository
        #project_dir: # optional, default is .
        # Format of the tag to be created, `*` is placeholder for actual version
        #tag_format: # optional, default is v*
        # API key for the NuGet feed
        #nuget_key: # optional
